<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>test.TestPlugin</PackageId>
    <Product>Test Plugin</Product>
    <Version>1.0.1-beta+69</Version>
    <Authors>Author, OtherAuthor</Authors>
    <RepositoryUrl>https://github.com/example/ExamplePlugin</RepositoryUrl>
    <TargetFramework>net10.0</TargetFramework>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <BepInAutoPluginStripBuildMetadata>true</BepInAutoPluginStripBuildMetadata>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ResoniteModding.BepInExResoniteShim" Version="0.9.*" />
    <ProjectReference Include="../BepInEx.AutoPlugin/BepInEx.AutoPlugin.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Import Project="../BepInEx.AutoPlugin/BepInEx.AutoPlugin.props" />

</Project>
