using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BepInEx.AutoPlugin;

[Generator]
public sealed class AutoPluginGenerator : IIncrementalGenerator
{
    public const string BepInAutoPluginAttributeName = "BepInAutoPluginAttribute";
    public const string PatcherAutoPluginAttributeName = "PatcherAutoPluginAttribute";

    public const string BepInAutoPluginAttributeFullName =
        "BepInEx." + BepInAutoPluginAttributeName;
    public const string PatcherAutoPluginAttributeFullName =
        "BepInEx.Preloader.Core.Patching." + PatcherAutoPluginAttributeName;

    const string BepInPluginAttribute = "BepInEx.BepInPlugin";
    const string ResonitePluginAttribute = "BepInExResoniteShim.ResonitePlugin";
    const string PatcherPluginInfoAttribute = "BepInEx.Preloader.Core.Patching.PatcherPluginInfo";

    const string AttributeCode = $$"""
        // <auto-generated />
        #pragma warning disable
        #nullable enable annotations

        namespace BepInEx
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            [global::System.Diagnostics.Conditional("CodeGeneration")]
            [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
            internal sealed class {{BepInAutoPluginAttributeName}} : global::System.Attribute
            {
                public {{BepInAutoPluginAttributeName}}(string? id = null, string? name = null, string? version = null, string? authors = null, string? link = null) {}
            }
        }

        namespace BepInEx.Preloader.Core.Patching
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            [global::System.Diagnostics.Conditional("CodeGeneration")]
            [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
            internal sealed class {{PatcherAutoPluginAttributeName}} : global::System.Attribute
            {
                public {{PatcherAutoPluginAttributeName}}(string? id = null, string? name = null, string? version = null) {}
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddEmbeddedAttributeDefinition();
            ctx.AddSource("BepInAutoPluginAttribute.g.cs", AttributeCode);
        });

        // First, collect all the data we might need
        var assemblyData = context.CompilationProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select(
                static (data, _) =>
                {
                    var (compilation, options) = data;
                    var globalOptions = options.GlobalOptions;

                    globalOptions.TryGetValue("build_property.PackageId", out var packageId);
                    globalOptions.TryGetValue("build_property.AssemblyName", out var assemblyName);
                    globalOptions.TryGetValue("build_property.Product", out var product);
                    globalOptions.TryGetValue("build_property.Version", out var version);
                    globalOptions.TryGetValue("build_property.Authors", out var authors);
                    globalOptions.TryGetValue("build_property.RepositoryUrl", out var repositoryUrl);

                    // Get InformationalVersion from assembly attributes
                    string? informationalVersion = null;
                    var attributes = compilation.Assembly.GetAttributes();
                    for (int i = 0; i < attributes.Length; i++)
                    {
                        var attribute = attributes[i];
                        var attributeClass = attribute.AttributeClass;

                        if (attributeClass == null)
                            continue;

                        if (attribute.ConstructorArguments.Length != 1)
                            continue;

                        string? expectedSystemNamespace = attributeClass
                            .ContainingNamespace
                            ?.ContainingNamespace
                            ?.MetadataName;

                        if (expectedSystemNamespace != "System")
                            continue;

                        var expectedReflectionNamespace = attributeClass
                            .ContainingNamespace!
                            .MetadataName;

                        if (expectedReflectionNamespace != "Reflection")
                            continue;

                        var className = attributeClass.MetadataName;

                        if (className == "AssemblyInformationalVersionAttribute")
                        {
                            informationalVersion = attribute.ConstructorArguments[0].Value as string;
                            break;
                        }
                    }

                    return (assemblyName, packageId, product, informationalVersion, version, authors, repositoryUrl);
                }
            );

        var references = context.CompilationProvider.Select(
            static (compilation, _) => compilation.ReferencedAssemblyNames
        );

        // BepInEx 5 doesn't support plugins having version pre-release or build metadata
        // such as 1.0.0-beta or 1.0.0+97ec53d20958b88581680d4d3c15ba59a8900ed5
        // so even if the user sets those in the project Version property,
        // we need to strip them out.
        IncrementalValueProvider<bool> isBepInEx5 = references.Select(
            static (refs, _) =>
            {
                var bepInEx = refs.FirstOrDefault(r => r.Name.Equals("BepInEx"));
                return bepInEx is not null && bepInEx.Version.Major == 5;
            }
        );

        IncrementalValueProvider<bool> shouldStripInformationalVersionBuildMetadata =
            context.AnalyzerConfigOptionsProvider.Select(
                static (options, _) =>
                {
                    var globalOptions = options.GlobalOptions;
                    globalOptions.TryGetValue(
                        "build_property.BepInAutoPluginStripBuildMetadata",
                        out var stripMetadata
                    );

                    bool shouldStripMetadata =
                        stripMetadata?.Equals("true", StringComparison.InvariantCultureIgnoreCase)
                        ?? false;

                    return shouldStripMetadata;
                }
            );

        // Now we have everything, combine and process the data
        IncrementalValueProvider<PluginProps> pluginProps = assemblyData
            .Combine(isBepInEx5)
            .Combine(shouldStripInformationalVersionBuildMetadata)
            .Select(
                static (items, _) =>
                {
                    var (
                        ((assemblyName, packageId, product, informationalVersion, version, authors, repositoryUrl), isBepInEx5),
                        shouldStripMetadata
                    ) = items;

                    string projectId = packageId ?? assemblyName ?? "unknown";
                    string projectName = product ?? projectId;
                    string projectVersion = informationalVersion ?? version ?? "0.0.0.0";
                    string projectAuthors = authors ?? "unknown";
                    string projectLink = repositoryUrl ?? "";

                    if (isBepInEx5)
                    {
                        projectVersion = projectVersion.Split('-', '+')[0];
                    }
                    else if (shouldStripMetadata)
                    {
                        projectVersion = projectVersion.Split('+')[0];
                    }

                    return new PluginProps(projectId, projectName, projectVersion, projectAuthors, projectLink);
                }
            );

        IncrementalValuesProvider<PluginClass> classesWithBepInAutoPlugin =
            GetPluginClassesWithAttribute(context, BepInAutoPluginAttributeFullName);

        context.RegisterSourceOutput(
            classesWithBepInAutoPlugin.Combine(pluginProps).Combine(isBepInEx5),
            static (context, source) =>
            {
                var ((plugin, props), isBepInEx5) = source;
                var attribute = isBepInEx5 ? BepInPluginAttribute : ResonitePluginAttribute;
                WriteClass(context, (plugin, props), attribute, includeAuthorsAndLink: true);
            }
        );

        IncrementalValuesProvider<PluginClass> classesWithPatcherAutoPlugin =
            GetPluginClassesWithAttribute(context, PatcherAutoPluginAttributeFullName);

        context.RegisterSourceOutput(
            classesWithPatcherAutoPlugin.Combine(pluginProps),
            static (context, source) => WriteClass(context, source, PatcherPluginInfoAttribute, includeAuthorsAndLink: false)
        );
    }

    static IncrementalValuesProvider<PluginClass> GetPluginClassesWithAttribute(
        IncrementalGeneratorInitializationContext context,
        string fullyQualifiedMetadataName
    ) =>
        context
            .SyntaxProvider.ForAttributeWithMetadataName(
                fullyQualifiedMetadataName,
                predicate: static (s, _) => IsValidPluginClass(s),
                transform: static (ctx, _) => ToPluginClass(ctx)
            )
            .Where(x => x != default);

    static bool IsValidPluginClass(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax { Parent: not TypeDeclarationSyntax } classSyntax)
        {
            return false;
        }

        if (!classSyntax.Modifiers.Any(SyntaxKind.PartialKeyword))
            return false;

        return true;
    }

    static PluginClass ToPluginClass(GeneratorAttributeSyntaxContext ctx)
    {
        var target = (ClassDeclarationSyntax)ctx.TargetNode;
        if (ctx.SemanticModel.GetDeclaredSymbol(target) is not INamedTypeSymbol typeSymbol)
        {
            return default;
        }

        var autoAttribute = ctx.Attributes.First();
        int argCount = autoAttribute.ConstructorArguments.Length;

        if (autoAttribute is null || argCount < 3 || argCount > 5)
            return default;

        string? id = autoAttribute.ConstructorArguments[0].Value as string;
        string? name = autoAttribute.ConstructorArguments[1].Value as string;
        string? version = autoAttribute.ConstructorArguments[2].Value as string;
        string? authors = argCount == 4 ? autoAttribute.ConstructorArguments[3].Value as string : null;
        string? link = argCount == 5 ? autoAttribute.ConstructorArguments[4].Value as string : null;

        var ns = typeSymbol.ContainingNamespace;
        var containingNamespace = ns.IsGlobalNamespace ? null : ns.ToDisplayString();

        return new PluginClass(
            containingNamespace,
            typeSymbol.Name,
            new PropOverrides(id, name, version, authors, link)
        );
    }

    static void WriteClass(
        SourceProductionContext context,
        (PluginClass plugin, PluginProps pluginProps) source,
        string attribute,
        bool includeAuthorsAndLink
    )
    {
        try
        {
            var (plugin, props) = source;

            StringBuilder sb = new();

            sb.AppendLine(
                """
                // <auto-generated />
                #pragma warning disable
                #nullable enable annotations

                """
            );

            PropOverrides overrides = plugin.Overrides;
            string id = SymbolDisplay.FormatLiteral(overrides.Id ?? props.Id, true);
            string name = SymbolDisplay.FormatLiteral(overrides.Name ?? props.Name, true);
            string version = SymbolDisplay.FormatLiteral(overrides.Version ?? props.Version, true);
            string authors = SymbolDisplay.FormatLiteral(overrides.Authors ?? props.Authors, true);
            string link = SymbolDisplay.FormatLiteral(overrides.Link ?? props.Link, true);
            string pluginClass = plugin.ClassName;

            if (plugin.Namespace is not null)
            {
                sb.Append("namespace ").AppendLine(plugin.Namespace).AppendLine("{");
            }

            if (!includeAuthorsAndLink)
            {
                sb.AppendLine($$"""[global::{{attribute}}({{pluginClass}}.GUID, {{pluginClass}}.NAME, {{pluginClass}}.VERSION)]""");
            }
            else
            {
                sb.AppendLine($$"""[global::{{attribute}}({{pluginClass}}.GUID, {{pluginClass}}.NAME, {{pluginClass}}.VERSION, {{pluginClass}}.AUTHORS, {{pluginClass}}.REPOSITORY_URL)]""");
            }

            sb.AppendLine($$"""
                    partial class {{pluginClass}}
                    {
                        /// <summary>
                        /// The Id of <see cref="{{pluginClass}}"/>.
                        /// </summary>
                        public const string GUID = {{id}};

                        /// <summary>
                        /// The name of <see cref="{{pluginClass}}"/>.
                        /// </summary>
                        public const string NAME = {{name}};

                        /// <summary>
                        /// The version of <see cref="{{pluginClass}}"/>.
                        /// </summary>
                        public const string VERSION = {{version}};
                """);

            if (includeAuthorsAndLink)
            {
                sb.AppendLine($$"""

                        /// <summary>
                        /// The authors of <see cref="{{pluginClass}}"/>. Separated by commas.
                        /// </summary>
                        public const string AUTHORS = {{authors}};

                        /// <summary>
                        /// The link of <see cref="{{pluginClass}}"/>.
                        /// </summary>
                        public const string REPOSITORY_URL = {{link}};
                """);
            }

            sb.AppendLine("""
                    }
                """);

            if (plugin.Namespace is not null)
            {
                sb.AppendLine("}");
            }

            var fileName = $"{plugin.Namespace}.{plugin.ClassName}.AutoPlugin.g.cs";
            context.AddSource(fileName, sb.ToString());
        }
        catch (Exception ex)
        {
            throw new Exception(ex.ToString().Replace('\n', ','));
        }
    }

    public readonly record struct PluginClass(
        string? Namespace,
        string ClassName,
        PropOverrides Overrides
    );

    public readonly record struct PropOverrides(string? Id, string? Name, string? Version, string? Authors, string? Link);

    public readonly record struct PluginProps(string Id, string Name, string Version, string Authors, string Link);
}
